# Server port
server:
  port: 8080

# Application name
spring:
  application:
    name: api-gateway
  # Configuring timeouts for the gateway's HTTP client
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

      # WebFlux configuration for CORS and routes
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "http://localhost:5173"
                  - "http://localhost"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          # Configuration of routes for microservices
          routes:
            # Orders microservice
            - id: order-service-route
              uri: http://order-service:8081
              predicates:
                - Path=/api/orders/**
              metadata:
                connect-timeout: 1000
                response-timeout: 5000
              filters:
                # Rate Limiting Filter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"
                # Retry filter with Retry
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                    methods: GET
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 500ms
                      factor: 2
                      basedOnPreviousValue: true
                # Circuit Breaker filter to handle faults in the microservice
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/orders

            # Inventory microservice
            - id: inventory-service-route
              uri: http://inventory-service:8082
              predicates:
                - Path=/api/products/**
              metadata:
                connect-timeout: 1000
                response-timeout: 3000
              filters:
                # Rate Limiting Filter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"
                # Retry filter with Retry
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                    methods: GET
                # Circuit Breaker filter to handle faults in the microservice
                - name: CircuitBreaker
                  args:
                    name: inventoryServiceCircuitBreaker
                    fallbackUri: forward:/fallback/inventory

            # Notifications microservice (WebSocket)
            - id: notification-service-ws-route
              uri: ws://notification-service:8083
              predicates:
                - Path=/ws/**,/ws

# Metrics and trace configuration
management:
  endpoints:
    web:
      exposure:
        # We expose the vital endpoints for Prometheus and health checks
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0 # 1.0 = Sends 100% of traces (ideal for development/demo)

  otlp:
    tracing:
      # Jaeger URL on the Docker Compose network using the HTTP OTLP port
      endpoint: http://jaeger:4318/v1/traces
  metrics:
    export:
      otlp:
        enabled: false # We disable OTLP metrics if you use Prometheus, to avoid conflicts
  opentelemetry:
    exporter:
      otlp:
        enabled: true
# Resilience4j configuration for Circuit Breaker that allows handling microservice failures and
# improving system resilience
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      inventoryServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true