server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Microservicio Pedidos
            - id: order-service-route
              uri: http://order-service:8081
              predicates:
                - Path=/api/orders/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            # Microservicio Inventario
            - id: inventory-service-route
              uri: http://inventory-service:8082
              predicates:
                - Path=/api/products/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            # Microservicio Notificaciones
            - id: notification-service-ws-route
              uri: ws://notification-service:8083
              predicates:
                - Path=/ws/**,/ws