# Automatic data source provisioning configuration for Grafana
apiVersion: 1

datasources:
  # Define Prometheus as the default data source
  - name: Prometheus
    type: prometheus
    access: proxy
    # Address of the Prometheus service within the Docker Compose network
    url: http://prometheus:9090
    isDefault: true
    editable: true