server:
  port: 8082

spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update

# Configuracion metricas y trazas
management:
  endpoints:
    web:
      exposure:
        # Exponemos los endpoints vitales para Prometheus y health checks
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0 # 1.0 = Envía el 100% de las trazas (ideal para desarrollo/demo)

  otlp:
    tracing:
      # URL de Jaeger en la red de Docker Compose usando el puerto HTTP OTLP
      endpoint: http://jaeger:4318/v1/traces
logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN